import unittest

from src import rss_fetcher
from src.title_style_validator import validate_title_style


class RssFetcherTitleStyleAlignmentTests(unittest.TestCase):
    def test_speculative_refactor_templates_return_fact_first_titles(self):
        cases = (
            {
                "name": "game_pregame_first_at_bat_with_opponent",
                "title": "【巨人】阪神戦で皆川岳飛がプロ初打席へ",
                "summary": "巨人のルーキー皆川岳飛が阪神戦でプロ初打席に向かう。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 初打席の注目選手",
                "expected_key": "game_pregame_first_at_bat",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_first_at_bat_without_opponent",
                "title": "【巨人】ドラ４ルーキーがプロ初打席へ",
                "summary": "巨人のルーキーがプロ初打席に向かう。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 初打席の注目選手情報",
                "expected_key": "game_pregame_first_at_bat",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_subject_with_opponent",
                "title": "阪神・佐藤輝明、衝撃の一発！辻発彦氏「強振している感じがしない」",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 佐藤輝明に関する試合前情報",
                "expected_key": "game_pregame_subject",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_subject_without_opponent",
                "title": "坂本勇人の調整状況",
                "summary": "巨人の坂本勇人が試合前練習で汗を流した。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 坂本勇人に関する試合前情報",
                "expected_key": "game_pregame_subject",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_venue_with_opponent",
                "title": "【一軍】巨人 vs 阪神 4/16(木)18:00試合開始予定⚾ 阪神甲子園球場",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 甲子園に関する試合前情報",
                "expected_key": "game_pregame_venue",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_venue_without_opponent",
                "title": "【一軍】巨人 4/16(木)18:00試合開始予定⚾ 東京ドーム",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 東京ドームに関する試合前情報",
                "expected_key": "game_pregame_venue",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_opponent",
                "title": "【巨人】阪神戦の試合前情報",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 当日カードの試合前情報",
                "expected_key": "game_pregame_opponent",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_generic",
                "title": "【巨人】試合開始前の最新情報",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 当日カードの試合前情報",
                "expected_key": "game_pregame_generic",
                "validator_subtype": "pregame",
            },
            {
                "name": "reinforcement_foreign",
                "title": "巨人の新外国人補強に注目",
                "summary": "",
                "category": "補強・移籍",
                "has_game": False,
                "expected_title": "巨人の新外国人補強 関連情報",
                "expected_key": "reinforcement_foreign",
                "validator_subtype": "notice",
            },
            {
                "name": "reinforcement_trade",
                "title": "巨人の補強・移籍とトレード動向",
                "summary": "",
                "category": "補強・移籍",
                "has_game": False,
                "expected_title": "巨人の補強・移籍 最新関連情報",
                "expected_key": "reinforcement_trade",
                "validator_subtype": "notice",
            },
            {
                "name": "reinforcement_generic",
                "title": "巨人補強の整理",
                "summary": "",
                "category": "補強・移籍",
                "has_game": False,
                "expected_title": "巨人補強の整理 関連トピック",
                "expected_key": "reinforcement_generic",
                "validator_subtype": "notice",
            },
            {
                "name": "player_status_deregister",
                "title": "【巨人】中山礼都が今季初抹消 OPS.393と苦戦 代役はルーキー皆川岳飛「２つの気持ち」",
                "summary": "巨人中山礼都外野手（24）が15日、今季初めて出場選手登録を抹消された。",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "中山礼都、登録抹消 関連情報",
                "expected_key": "player_status_deregister",
                "validator_subtype": "notice",
            },
            {
                "name": "player_status_join",
                "title": "【巨人】グリフィンが一軍合流 先発ローテ候補として再調整完了",
                "summary": "先発ローテ候補として一軍に合流した。次回登板へ向けた調整段階にある。",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "グリフィン、一軍合流 関連情報",
                "expected_key": "player_status_join",
                "validator_subtype": "notice",
            },
            {
                "name": "player_status_register_notice_type",
                "title": "【巨人】皆川岳飛が出場選手登録",
                "summary": "皆川岳飛外野手が出場選手登録された。",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "皆川岳飛、一軍登録 関連情報",
                "expected_key": "player_status_register",
                "validator_subtype": "notice",
            },
            {
                "name": "player_status_register_generic",
                "title": "【巨人】皆川岳飛が支配下登録",
                "summary": "皆川岳飛が支配下登録された。",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "皆川岳飛、登録に関する関連情報",
                "expected_key": "player_status_register",
                "validator_subtype": "notice",
            },
            {
                "name": "player_status_return",
                "title": "巨人・吉川尚輝がマルチ安打で調整上々「体もいい感じだし、しっかり野球をできた」１軍復帰へ着実",
                "summary": "巨人・吉川尚輝がマルチ安打で調整上々「体もいい感じだし、しっかり野球をできた」１軍復帰へ着実",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "吉川尚輝、昇格・復帰 関連情報",
                "expected_key": "player_status_return",
                "validator_subtype": "notice",
            },
            {
                "name": "player_quote",
                "title": "【巨人】田中将大「打線を線にしない」甲子園の“申し子”が移籍後初の阪神戦で好投誓う",
                "summary": "田中将大が移籍後初の阪神戦に向け「打線を線にしない」と話した。",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "田中将大「打線を線にしない」 関連発言",
                "expected_key": "player_quote",
                "validator_subtype": "notice",
            },
            {
                "name": "player_mechanics_generic",
                "title": "【巨人】大胆フォーム変更の戸郷翔征「人の助言を取り入れることも重要」久保コーチとの取り組み",
                "summary": "ファームでフォーム改造中の巨人戸郷翔征投手が調整した。",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "戸郷翔征、フォーム変更 関連情報",
                "expected_key": "player_mechanics_generic",
                "validator_subtype": "notice",
            },
            {
                "name": "player_generic",
                "title": "【巨人】田中将大が２軍戦で先発へ",
                "summary": "田中将大が2軍戦で先発する予定。",
                "category": "選手情報",
                "has_game": False,
                "expected_title": "田中将大の現状整理 関連情報",
                "expected_key": "player_generic",
                "validator_subtype": "notice",
            },
            {
                "name": "manager_quote_lineup",
                "title": "【巨人】阿部監督「打順は相手を見て決める」スタメン再編を示唆",
                "summary": "阿部監督が「打順は相手を見て決める」と話し、スタメン再編を示唆した。",
                "category": "首脳陣",
                "has_game": False,
                "expected_title": "阿部監督「打順は相手を見て決める」 スタメン関連発言",
                "expected_key": "manager_quote_lineup",
                "validator_subtype": "manager",
            },
            {
                "name": "manager_quote_generic",
                "title": "「彼が打ったらもっと打線が機能する」巨人・阿部監督、身ぶり手ぶりでダルベックを２０分間熱血指導",
                "summary": "「彼が打ったらもっと打線が機能する」巨人・阿部監督、身ぶり手ぶりでダルベックを２０分間熱血指導",
                "category": "首脳陣",
                "has_game": False,
                "expected_title": "阿部監督「彼が打ったらもっと打線が機能する」 ベンチ関連発言",
                "expected_key": "manager_quote_generic",
                "validator_subtype": "manager",
            },
            {
                "name": "manager_generic",
                "title": "【巨人】阿部監督が起用方針を説明",
                "summary": "阿部監督が今後のチーム運営方針について説明した。",
                "category": "首脳陣",
                "has_game": False,
                "expected_title": "阿部コメント整理 ベンチ関連の発言ポイント",
                "expected_key": "manager_generic",
                "validator_subtype": "manager",
            },
            {
                "name": "game_rainout_slide_rainout",
                "title": "【巨人】雨天中止で先発予定だった田中将大は16日にスライド登板 村田善則コーチ明かす",
                "summary": "巨人田中将大投手（37）が雨天中止にともなってスライド登板することになった。",
                "category": "試合速報",
                "has_game": False,
                "expected_title": "田中将大、雨天中止スライド登板 関連情報",
                "expected_key": "game_rainout_slide_rainout",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_rainout_slide_venue",
                "title": "【巨人】甲子園で勝てば16年ぶり 田中将大16日スライド登板「勝利につなげる投球」",
                "summary": "",
                "category": "試合速報",
                "has_game": False,
                "expected_title": "田中将大、甲子園スライド登板 関連情報",
                "expected_key": "game_rainout_slide_venue",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_rainout_slide_opponent",
                "title": "【巨人】田中将大が阪神戦へスライド登板",
                "summary": "田中将大が阪神戦でスライド登板する見込み。",
                "category": "試合速報",
                "has_game": False,
                "expected_title": "田中将大、阪神戦スライド登板 関連情報",
                "expected_key": "game_rainout_slide_opponent",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_rainout_slide_generic",
                "title": "【巨人】田中将大が16日にスライド登板",
                "summary": "田中将大がスライド登板する見込み。",
                "category": "試合速報",
                "has_game": False,
                "expected_title": "田中将大、スライド登板 関連情報",
                "expected_key": "game_rainout_slide_generic",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_live_tie",
                "title": "【巨人途中経過】7回表 巨人3-3阪神と同点",
                "summary": "巨人戦は7回表の時点で阪神に3-3と追いついた。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人7回表 3-3 同点の試合状況",
                "expected_key": "game_live_tie",
                "validator_subtype": "postgame",
            },
            {
                "name": "farm_lineup",
                "title": "【二軍】巨人対DeNA 4番ショートでスタメン",
                "summary": "巨人の二軍スタメンが発表された。",
                "category": "ドラフト・育成",
                "has_game": True,
                "expected_title": "巨人二軍スタメン 当日カード試合前情報",
                "expected_key": "farm_lineup",
                "validator_subtype": "farm",
            },
            {
                "name": "game_postgame_shutout_with_opponent",
                "title": "【巨人】今季２度目の０封負けで連敗　井上温大は６回２失点も打線が沈黙",
                "summary": "巨人はヤクルト投手陣を攻略できず、今季2度目の0封負けを喫した。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人ヤクルト戦 打線沈黙 試合内容の整理",
                "expected_key": "game_postgame_shutout",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_shutout_without_opponent",
                "title": "【巨人】打線が沈黙し完封負け",
                "summary": "巨人は打線が沈黙し、完封負けを喫した。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 打線沈黙 試合内容の整理",
                "expected_key": "game_postgame_shutout",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_clutch_with_opponent",
                "title": "【巨人】阪神戦で決勝打、延長戦を制す",
                "summary": "阪神戦で決勝打が飛び出し、巨人が勝利した。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 終盤の一打で動いた試合",
                "expected_key": "game_postgame_clutch",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_clutch_without_opponent",
                "title": "【巨人】サヨナラ勝ちで決勝打",
                "summary": "巨人がサヨナラ勝ちを収め、決勝打が生まれた。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 終盤の一打で動いた試合",
                "expected_key": "game_postgame_clutch",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_hero",
                "title": "【一軍】巨人 4-3 阪神 本日のヒーロー✨ 3安打3打点1本塁打の活躍を見せた 選手💪 HERO IS HERE!",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人4-3 試合を決めたヒーロー",
                "expected_key": "game_postgame_hero",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_subject_comment_with_opponent",
                "title": "【巨人】田中将大、初の「伝統の一戦」で野茂超え日米通算202勝目「皆に助けられた」一問一答",
                "summary": "阪神戦後の一問一答。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 田中将大の試合後発言整理",
                "expected_key": "game_postgame_subject_comment",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_subject_comment_without_opponent",
                "title": "【巨人】勝利後の田中将大投手一問一答「皆に助けられた」",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 田中将大の試合後発言整理",
                "expected_key": "game_postgame_subject_comment",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_subject_analysis_with_opponent",
                "title": "【巨人】阪神戦勝利後の田中将大投手の投球術を分析",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 田中将大の強み 試合後の整理",
                "expected_key": "game_postgame_subject_analysis",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_subject_analysis_without_opponent",
                "title": "【巨人】勝利後の田中将大投手の投球術を分析",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 田中将大の強み 試合後の整理",
                "expected_key": "game_postgame_subject_analysis",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_subject_with_opponent",
                "title": "【巨人】田中将大が野茂英雄超え日米通算202勝目！伝統の一戦は昨季から10試合連続１点差",
                "summary": "阪神戦で田中将大が勝利した。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 田中将大、試合での見せ場",
                "expected_key": "game_postgame_subject",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_subject_without_opponent",
                "title": "【巨人】田中将大が好投で白星",
                "summary": "田中将大が好投し、白星をつかんだ。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 田中将大、試合での見せ場",
                "expected_key": "game_postgame_subject",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_supporting_point_with_opponent",
                "title": "【とっておきメモ】２勝目巨人田中将大の強み「体をバランス良く使えている」ブルペン捕手が証言",
                "summary": "阪神戦で田中将大を支えた要素を証言。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 勝利を支えた材料の整理",
                "expected_key": "game_postgame_supporting_point",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_supporting_point_without_opponent",
                "title": "【とっておきメモ】4-3勝利を支えた材料を証言",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 勝利を支えた材料の整理",
                "expected_key": "game_postgame_supporting_point",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_loss",
                "title": "【巨人】9回裏に競り負けて敗戦",
                "summary": "9回裏 巨人2-4阪神。敗戦を喫した。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人2-4 敗戦の分岐点 試合の流れ",
                "expected_key": "game_postgame_loss",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_postgame_win",
                "title": "【巨人】接戦を制して勝利",
                "summary": "巨人8-2ヤクルト。白星を挙げて連勝とした。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人8-2 勝利の分岐点 試合の流れ",
                "expected_key": "game_postgame_win",
                "validator_subtype": "postgame",
            },
            {
                "name": "game_pregame_subject_starter_with_opponent",
                "title": "【１６日の予告先発】阪神・ルーカス―巨人・田中将大、ロッテ・木村優人―日本ハム・",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 田中将大先発 試合前情報",
                "expected_key": "game_pregame_subject_starter",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_subject_starter_without_opponent",
                "title": "【巨人】先発は田中将大",
                "summary": "田中将大が先発する見込み。",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 田中将大先発 試合前情報",
                "expected_key": "game_pregame_subject_starter",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_numeric_with_opponent",
                "title": "【4/16予告先発】阪神戦 ー （甲子園、18:00) 巨人:(1勝0敗、防御率1.4",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人阪神戦 予告先発 関連数字情報",
                "expected_key": "game_pregame_numeric",
                "validator_subtype": "pregame",
            },
            {
                "name": "game_pregame_numeric_without_opponent",
                "title": "【4/16予告先発】 ー （東京ドーム、18:00) 巨人:(1勝0敗、防御率1.4",
                "summary": "",
                "category": "試合速報",
                "has_game": True,
                "expected_title": "巨人戦 予告先発 関連数字情報",
                "expected_key": "game_pregame_numeric",
                "validator_subtype": "pregame",
            },
        )

        for case in cases:
            with self.subTest(case=case["name"]):
                rewritten, template_key = rss_fetcher._rewrite_display_title_with_template(
                    case["title"],
                    case["summary"],
                    case["category"],
                    case["has_game"],
                )
                self.assertEqual(rewritten, case["expected_title"])
                self.assertEqual(template_key, case["expected_key"])
                result = validate_title_style(rewritten, case["validator_subtype"])
                self.assertTrue(result.ok, msg=f"{case['name']}: {result}")


if __name__ == "__main__":
    unittest.main()
