"""Narrow lineup-table post-process for RSS auto-fetcher bodies.

Detects prose-style "N番 守備 選手" lineup blocks in RSS auto-fetcher body
HTML and replaces them with an HTML <table>, plus the nomotoke-card-*
markers so the downstream ``apply_rss_pipeline_enrichment`` activates.

Gated by ``ENABLE_RSS_LINEUP_TABLE_POST_PROCESS`` env flag (default OFF).
When the flag is OFF or the gate conditions are not met, the function
returns the input unchanged.

Why narrow:
  * The 23k-line ``rss_fetcher`` is generated by Gemini long-form prose;
    a full nomotoke-renderer wiring would require structured-data flow
    that does not currently exist on the RSS auto path. This module
    accepts the prose body as-is and only transforms a clearly
    recognisable lineup block into a table without touching the rest of
    the body, the Gemini call, the template routing, or any env / mail /
    scheduler / Cloud Run setting.
"""

from __future__ import annotations

import os
import re
from typing import Callable, List, Optional

ENABLE_RSS_LINEUP_TABLE_POST_PROCESS_ENV = "ENABLE_RSS_LINEUP_TABLE_POST_PROCESS"

# Template-key fragments treated as "lineup-style" for this post-process.
_LINEUP_TEMPLATE_FRAGMENTS = ("lineup", "farm_lineup")

# Minimum number of consecutive batter-line matches before we treat the
# block as a lineup. 8 = 8 position players (DH-less, pitcher 9th).
_MIN_LINEUP_LINE_COUNT = 8

_PARA_LINEUP_RE = re.compile(
    r"<p>\s*"
    r"([1-9一二三四五六七八九])番"
    r"[\s　]+(\S+)"
    r"[\s　]+([^<\s]+)"
    r"[\s　]*</p>",
    re.UNICODE,
)

_TRUTHY_ENV_VALUES = frozenset({"1", "true", "yes", "on"})


def _flag_on(env_getter: Callable[[str], Optional[str]]) -> bool:
    value = (env_getter(ENABLE_RSS_LINEUP_TABLE_POST_PROCESS_ENV) or "").strip().lower()
    return value in _TRUTHY_ENV_VALUES


def _template_is_lineup(template_key: str) -> bool:
    key = (template_key or "").lower()
    return any(fragment in key for fragment in _LINEUP_TEMPLATE_FRAGMENTS)


def _content_has_nomotoke_marker(content: str) -> bool:
    return 'class="nomotoke-card-' in content or "class='nomotoke-card-" in content


def _find_lineup_block(content: str) -> Optional[List[dict]]:
    matches = list(_PARA_LINEUP_RE.finditer(content))
    if len(matches) < _MIN_LINEUP_LINE_COUNT:
        return None
    rows = [
        {
            "num": m.group(1),
            "pos": m.group(2).strip(),
            "name": m.group(3).strip(),
            "start": m.start(),
            "end": m.end(),
        }
        for m in matches
    ]
    for i in range(1, len(rows)):
        if content[rows[i - 1]["end"]:rows[i]["start"]].strip():
            return None
    return rows


def _render_lineup_table_html(rows: List[dict]) -> str:
    body = "".join(
        "<tr>"
        f"<td>{row['num']}番</td>"
        f"<td>{row['pos']}</td>"
        f"<td>{row['name']}</td>"
        "</tr>"
        for row in rows
    )
    return (
        '<table class="nomotoke-card-lineup-table">'
        "<thead><tr><th>打順</th><th>守備</th><th>選手</th></tr></thead>"
        f"<tbody>{body}</tbody>"
        "</table>"
    )


def _wrap_with_nomotoke_markers(table_html: str) -> str:
    return (
        table_html
        + '<hr class="nomotoke-card-divider">'
        + '<div class="nomotoke-card-footer">参考: スポーツ報知</div>'
    )


def inject_lineup_table_if_enabled(
    content: str,
    template_key: str,
    env_getter: Callable[[str], Optional[str]] = os.environ.get,
) -> str:
    """Inject an HTML <table> for the detected lineup block and return the
    modified content. Returns the input unchanged when any gate condition
    is not satisfied.

    Gate conditions (ALL required):
      * Flag ON via ``env_getter``.
      * ``template_key`` looks like a lineup template.
      * Content does NOT already carry the ``nomotoke-card-`` marker.
      * Content contains an 8+-line consecutive "N番 守備 選手" prose block.
    """
    if not content:
        return content
    if not _flag_on(env_getter):
        return content
    if not _template_is_lineup(template_key):
        return content
    if _content_has_nomotoke_marker(content):
        return content
    rows = _find_lineup_block(content)
    if not rows:
        return content

    decorated = _wrap_with_nomotoke_markers(_render_lineup_table_html(rows))
    return content[:rows[0]["start"]] + decorated + content[rows[-1]["end"]:]
